name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        image: [sftp]
    steps:
      - uses: actions/checkout@v4
      - name: Read image config
        id: config
        run: |
          DF="images/${{ matrix.image }}/Dockerfile"
          IMAGE=$(grep -m1 '^# image:' "$DF" | sed 's/^# image: *//')
          [ -z "$IMAGE" ] && echo "::error::Missing '# image:' in $DF" && exit 1
          RAW_TAGS=$(grep -m1 '^# tags:' "$DF" | sed 's/^# tags: *//')
          [ -z "$RAW_TAGS" ] && RAW_TAGS="latest"
          TAGS=$(echo "$RAW_TAGS" | tr ',' '\n' | sed "s/^ *//;s/ *$//;s|^|${IMAGE}:|" | paste -sd,)
          echo "tags=$TAGS" >> "$GITHUB_OUTPUT"
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: images/${{ matrix.image }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.config.outputs.tags }}
          labels: |
            org.opencontainers.image.source=https://github.com/StephanMeijer/Dockerfile
